evry_thing_galerie_albums:
    pattern:  /albums
    defaults: { _controller: EvryThingGalerieBundle:Galerie:albums }

evry_thing_galerie_carrousel:
    pattern:  /carrousel/{album}
    defaults: { _controller: EvryThingGalerieBundle:Galerie:carrousel }

evry_thing_galerie_upload:
    pattern:  /upload
    defaults: { _controller: EvryThingGalerieBundle:Galerie:upload }

evry_thing_galerie_admin:
    pattern:  /admin
    defaults: { _controller: EvryThingGalerieBundle:Galerie:admin }
