parameters:
#    evry_thing_user.example.class: EvryThing\UserBundle\Example

services:
#    evry_thing_user.example:
#        class: %evry_thing_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
